# fly.toml app configuration file generated for rss-ai-analyzer on 2024-09-30T00:27:24+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rss-ai-analyzer'
primary_region = 'cdg'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]
  builder = 'paketobuildpacks/builder:base'

[env]
  FLET_SESSION_TIMEOUT = '60'
  PORT = '8000'
  FLET_SERVER_PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 250
    soft_limit = 200

[[vm]]
  size = 'shared-cpu-1x'
